version: "3.9"

services:
  wishlist_db:
    image: postgres:17
    restart: always
    container_name: wishlist_db
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=wishlist_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass